### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by NavaShield** [SpookySec/BSInternalPublic#3]
idk if this is still worked on so 🤷‍♂️

Features:
- Wireframe ESP/Skeleton ESP
- Noclip
- Flight
- Teleportation
- Wallbang

mrrp meow mroww :333

**Comment by SpookySec** [comment]
idk last I checked, I don't work for an it/it.

Go find God before worshipping your desire for s**.

**Comment by NavaShield** [comment]
> idk last I checked, I don't work for an it/it.
> 
> Go find God before worshipping your desire for s**.

im not an it/it but ok then 💀
also in your readme.md you literally are requesting inspiration so 🤷

**Comment by SpookySec** [comment]
#That's fair, I did write that in, it's just when someone's entire existence is revolved about their sexual identity (which I believe is all nonsense), I immediately lose interest in that person or even listening to what they have to say, I see your name as "overlord of c**" and think: "wow, what has this kid seen and been through to end up like this", and then your bio says "being g**", it just shows how empty and hollow you are from the inside, and i'm not attacking or blaming you for it, you were born and raised that way, it just makes me sad that that's how kids are being raised in today's world.

I apologize for my aggressive reply; I'll try to work on (some) of the features you asked for (I'm very busy these days so might not be that soon).

May God bless you.

**Comment by NavaShield** [comment]
thank you
![image](https://github.com/SpookySec/BSInternalPublic/assets/88568085/4da90aff-d654-45f6-b064-92a89ddbd228)
